---
- name: Testing event-driven automation
  hosts: all

  sources:
    - ansible.eda.range:
        limit: 10

  rules:
    - name: debug
      condition: event.i == 3
      action:
        debug:
          msg: "hogehogehogehogehogeogh"
    - name: Output a message
      condition: event.i > 0
      action:
        debug:
          msg: "Happy Automation!"
