---
- name: Testing event-driven automation
  hosts: all

  sources:
    - ansible.eda.range:
        limit: 10

  rules:
    - name: shutdown
      condition: event.i == 3
      action:
        ansible.eda.shutdown:
          delay: 0.125
          message: Shutting down after 3 events

    - name: Output a message
      condition: event.i > 0
      action:
        ansible.eda.debug:
          msg: "Happy Automation!"
